# Muhammad Rizky Fajriawan

ğŸ‘¨â€ğŸ’» UI Designer  
ğŸ“ Indonesia  
ğŸ“« Email: rfajriawan@gmail.com  

## âœ¨ Projects

- ğŸ¨ **Design System UI** â€“ Situ Unpas

## ğŸ“ Skills

- HTML, CSS, JavaScript, React  
- Figma, Adobe XD  

## ğŸ“¬ Contact Me

- [LinkedIn](https://www.linkedin.com/in/rizky-fajriawan-6a82992b2/)
- [Instagram](https://www.instagram.com/rizkyfajriawan_)
- [Tiktok](https://www.tiktok.com/@rizkyfajriawan)
